repos:
  # general checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: pretty-format-json
        args: [ --autofix ]

  # Poetry - Dependency management
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
  
  # Sync pre-commit versions with poetry versions
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "0.4.0"
    hooks:
      - id: sync_with_poetry
        args: [] # optional args

   # black - formatting python
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        language_version: python3.10
        args: [ backend/ ]
  
  # flake8 - linting python
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [ backend/]

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier