repos:
  # general checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier

  - repo: local
    hooks:
      # Poetry - Dependency Management
      - id: poetry-check
        name: poetry-check
        language: system
        entry: bash -c 'cd backend && exec poetry check'
        files: ^backend/
      - id: poetry-lock
        name: poetry-lock
        language: system
        entry: bash -c 'cd backend && exec poetry check'
        files: ^backend/

      # Black - formatting Python
      - id: black
        name: black
        language: system
        entry: bash -c 'cd backend && exec poetry run black .'
        files: ^backend/

      # flake8 - linting python
      - id: flake8
        name: flake8
        language: system
        entry: bash -c 'cd backend && exec poetry run flake8 .'
        files: ^backend/

      # isort - reorder imports
      - id: isort
        name: isort
        language: system
        entry: bash -c 'cd backend && exec poetry run isort . --profile black'
        files: ^backend/
