version: "3.8"

services:
  parsnip-backend:
    container_name: parsnip-backend
    build: ./backend
    ports:
      - "8000:8000"

  react_native_app:
    build: ./frontend
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
    volumes:
      - /app/node_modules
