"""add device auth to model

Revision ID: 0e2e991a419e
Revises: fc23c5096b5e
Create Date: 2023-04-20 16:13:38.912023

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e2e991a419e"
down_revision = "fc23c5096b5e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("devices", sa.Column("auth_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "auth_token")
    # ### end Alembic commands ###
