"""Removed test migration

Revision ID: 6f1175ef1088
Revises: dbc28842216c
Create Date: 2023-03-21 13:10:11.042912

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f1175ef1088"
down_revision = "dbc28842216c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
