"""init

Revision ID: d35247d12574
Revises: 
Create Date: 2023-03-21 00:29:26.876104

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d35247d12574"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
