"""Removed test migration

Revision ID: dbc28842216c
Revises: e1cb5aab3dcb
Create Date: 2023-03-21 13:02:07.402996

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dbc28842216c"
down_revision = "e1cb5aab3dcb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_profile_images_id", table_name="profile_images")
    op.drop_table("profile_images")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_images",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("img_path", sa.VARCHAR(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_profile_images_id", "profile_images", ["id"], unique=False)
    # ### end Alembic commands ###
