"""First migration

Revision ID: e1cb5aab3dcb
Revises: d35247d12574
Create Date: 2023-03-21 00:43:41.022735

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1cb5aab3dcb"
down_revision = "d35247d12574"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("img_path", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_profile_images_id"), "profile_images", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_images_id"), table_name="profile_images")
    op.drop_table("profile_images")
    # ### end Alembic commands ###
