name: Docker Image CI

on:
  push:
    branches: ["main", "backend"]
  pull_request:
    branches: ["main", "backend"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Backend Docker image
        working-directory: ./backend
        run: |
          docker build . --file Dockerfile --tag parsnip-backend:${{github.run_id}}

      - name: Run pytest inside of Backend Docker image
        working-directory: ./backend
        run: |
          docker run parsnip-backend:${{github.run_id}} pytest
