name: React Unit Tests

on:
  push:
    branches: ["main", "frontend"]
  pull_request:
    branches: ["main", "frontend", "development"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    container:
      image: node:18-alpine

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies, build, and test
        working-directory: ./frontend
        run: |
          npm ci --legacy-peer-deps
          npm run build --if-present
          npm test